.\" Manpage tvshowfile.exceptman ExceptionList Dictionary.
.\" Contact baspann@gmail.com to correct errors or typos.
.TH man 1 "26 12 2018" "1.0" "util man page"
.SH NAME
myCoammand \- create a new LDAP user
.SH SYNOPSIS
myCoammand
.SH DESCRIPTION
myCoammand is a simple python script for editing the contents of the exceptionlist.json file located under the python module tvshowfile/ in the directory "data"
.SH OPTIONS
The myCoammand does not take any options.
.IP l
Will list all keys and sub keys with their values
.IP k
Will allow you to enter a key to get the nested keys and their values.
.IP a
Will add a new key
.IP s
Will save the contents of the ExceptionListManager if the managers values have been changed.
.\".SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Adam Spann (baspann@gmail.com)
